[WIP][docs] update Python-package installation guide
lightgbm-org/LightGBM pull request #6767
Opened 2024-12-26 05:23 UTC by StrikerRUS

2024-12-26 06:29 UTC, StrikerRUS commented on python-package/README.rst
> +Warning: Dask-package is only tested on Linux.
Neither GitHub nor PyPI have options to render `warning` / `note` directives.
https://github.com/github/markup/issues/72

![image](https://github.com/user-attachments/assets/41fe86ee-63ca-4f8f-95a3-146149aecc0d)

2024-12-26 06:29 UTC, StrikerRUS commented on python-package/README.rst
> +Use LightGBM with Matplotlib and Graphviz
For the completeness.

2024-12-26 06:29 UTC, StrikerRUS commented on python-package/README.rst
> +    pip install lightgbm --no-binary lightgbm --config-settings=cmake.define.USE_OPENMP=OFF
Without `--no-binary` flag `pip` doesn't try to build from sources but simply installs precompiled wheel file regardless specified `--config-settings` flags.

2024-12-26 06:29 UTC, StrikerRUS commented on python-package/README.rst
> -    # in sh.exe, git bash, or other Unix-like shell
Now this command work in any shell.

2024-12-26 06:29 UTC, StrikerRUS commented on python-package/README.rst
> +These packages support **CPU**, **GPU** and **CUDA** versions out of the box.
Simplify a little bit.

2024-12-26 06:29 UTC, StrikerRUS commented on python-package/README.rst
> -Run ``sh ./build-python.sh install --mingw``, if you want to use **MinGW-w64** on **Windows** instead of **Visual Studio**. All requirements from `Build with MinGW-w64 on Windows section <#build-with
Keep the same order as in the `Install from PyPI -> Build from Sources` section.

2025-01-19 18:59 UTC, StrikerRUS commented on python-package/README.rst
> +    pip install lightgbm --no-binary lightgbm --config-settings=cmake.define.USE_GPU=ON --config-settings=cmake.define.OpenCL_INCLUDE_DIR="/usr/local/cuda/include/" --config-settings=cmake.define.Ope
We cannot predict which shell user is using. For example, to split long line in PowerShell ` char should be used.

2025-01-23 05:01 UTC, jameslamb requested changes
Thanks for this! I left some suggestions for your consideration.

2025-01-23 05:01 UTC, jameslamb commented on python-package/pyproject.toml
> +
What is the benefit of moving these things down here? Are the equivalent fields in `[tool.scikit-build]` deprecated?

2025-01-26 16:21 UTC, StrikerRUS commented on python-package/pyproject.toml
> +
Huh, these nested fields are identical, I simply don't know how to specify nested mapping `tool.scikit-build.cmake.define` in existing setup 😬

2025-01-26 17:23 UTC, jameslamb commented on python-package/pyproject.toml
> +
I agree with you about that, I'd expected that this form would work:

```toml
[tool.scikit-build]
cmake.define = [
  "__BUILD_FOR_PYTHON=ON",
  "some_new_option=value"
]
```

But when I search around on GitHub, I don't see any examples like that: https://github.com/search?q=%22cmake.define%22+language%3ATOML&type=code&p=1

Let's leave this as you have it in the PR, I like it.

2025-01-30 23:02 UTC, StrikerRUS commented on python-package/README.rst
> +If you get any errors during installation or due to any other reasons, you may want to build dynamic library from sources by any method you prefer (see `Installation Guide <https://github.com/microso
Sure thing! Do you want me to split lines in the whole file or only in the touched paragraphs?

2025-01-30 23:17 UTC, jameslamb commented on python-package/README.rst
> +If you get any errors during installation or due to any other reasons, you may want to build dynamic library from sources by any method you prefer (see `Installation Guide <https://github.com/microso
I'm ok with it being every line in the file, I don't mind reviewing that.

But also fine if you want to do that in a later PR (or want me to do it, since it's my annoying suggestion 😅 )

2025-02-10 22:25 UTC, StrikerRUS commented on python-package/README.rst
> -Use them instead of ``pip install`` if any of the following are true:
Got it! Thanks for your detailed response!

2025-02-11 00:13 UTC, StrikerRUS commented on python-package/README.rst
> +If you get any errors during installation or due to any other reasons, you may want to build dynamic library from sources by any method you prefer (see `Installation Guide <https://github.com/microso
Done in https://github.com/microsoft/LightGBM/pull/6767/commits/c8c4bca87bb2b8c03c1ce1690237dce4fd1490d3.

2025-03-02 17:51 UTC, StrikerRUS commented
@jameslamb I think I addressed all your comments. Please give another look at this PR.

2025-03-26 01:10 UTC, jameslamb commented on build-python.sh
> +            exit 1
Thank you for catching that!

2025-03-26 01:11 UTC, jameslamb commented on build-python.sh
> +    echo "--sdist --outdir ../dist ${BUILD_ARGS} ." | xargs python -m build
Oh interesting, good idea!

2025-03-26 01:13 UTC, jameslamb commented on python-package/README.rst
> -- Starting from version 2.2.1, the library file in distribution wheels is built by the **Apple Clang** (Xcode_8.3.3 for versions 2.2.1 - 2.3.1, Xcode_9.4.1 for versions 2.3.2 - 3.3.2 and Xcode_11.7 f
I agree! At some point, maintaining all this old information hurts clarity more than it helps.

2025-03-26 01:30 UTC, jameslamb approved these changes
This looks great to me! I think all of my initial comments have been addressed. Thank you very much for all of your hard work, especially for testing all of these different installation methods.

2025-04-17 09:39 UTC, merged